version: "3.8"

services:
  gelrss:
    build: .
    environment:
      - NODE_ENV=production
    container_name: gelrss
    restart: unless-stopped
    env_file: .env
    ports:
      - "24454:24454"
    volumes:
      - ./configs:/home/node/app/configs:ro
      - ./data:/home/node/app/data
